version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install --production
      - cd scripts/build-links && yarn install --production && cd ../..

  build:
    commands:
      - cd scripts/build-links && node buildApiUrls.js stage=dev && cd ../..
      - yarn build --production

  post_build:
    commands:
      - aws s3 sync ./build/public s3://$REACT_OUTPUT --delete
