version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - npm install -g yarn@0.17.8
      - yarn

  build:
    commands:
      - yarn build

  post_build:
    commands:
      - aws s3 sync ./build/public s3://$REACT_OUTPUT --delete
