version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - pip install hesdeploy
      - npm install -g yarn

  build:
    commands:
      - cd deploy/web && hesdeploy -s prep --update && cd ..

  post_build:
    commands:
