version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - pip install hesdeploy
      - python -c "import site; print(site.getsitepackages())"
      - python -m site --user-site
      - pip list --user
      - npm install -g yarn

  build:
    commands:
      - hesdeploy -s prep --update

  post_build:
    commands:
