version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
      - cd scripts/build-links && yarn install --production && cd ../..

  build:
    commands:
      - cd scripts/build-links
      - node buildConfig.js stage=prep
      - REACT_OUTPUT=$(node getStageBucket.js stage=prep)
      - cd ../..
      - yarn build --production

  post_build:
    commands:
      - echo $REACT_OUTPUT
      - aws s3 sync ./build/public s3://$REACT_OUTPUT --delete
