version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - pip install hesburgh-utilities
      - npm install -g yarn

  build:
    commands:
      - hesdeploy -s prep --update

  post_build:
    commands:
            
