version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - pip install hesdeploy
      - ls /usr/local/lib/python2.7/dist-packages
      - ls /usr/lib/python2.7/dist-packages
      - ls /root/.local/lib/python2.7/site-packages
      - ls /usr/local/bin
      - npm install -g yarn

  build:
    commands:
      - hesdeploy -s prep --update

  post_build:
    commands:
