AWSTemplateFormatVersion: "2010-09-09"
Description: "Resources for codebuild stack"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  OutBucket:
    Type: String
    Description: The bucket to write to
  RoleArn:
    Type: String
    Description: Arn of the Execution Role

  ViceroyApi:
    Type: String
    Description: The ViceroyApi to use during build
  RecommendApi:
    Type: String
    Description: The RecommendApi to use during build
  CoursesApi:
    Type: String
    Description: The CoursesApi to use during build
  ResourcesApi:
    Type: String
    Description: The ResourcesApi to use during build
  IlliadBaseUrl:
    Type: String
    Description: The IlliadBaseUrl to use during build
  HoursApiUrl:
    Type: String
    Description: The HoursApiUrl to use during build
  ContentfulApi:
    Type: String
    Description: The ContentfulApi to use during build

Resources:
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ServiceName
      Description: !Sub usurper Codebuild
      ServiceRole: !Ref RoleArn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:7.0.0
        EnvironmentVariables:
        - Name: REACT_OUTPUT
          Value: !Ref OutBucket

        - Name: VICEROY_API
          Value: !Ref ViceroyApi
        - Name: RECOMMEND_API
          Value: !Ref RecommendApi
        - Name: COURSES_API
          Value: !Ref CoursesApi
        - Name: RESOURCES_API
          Value: !Ref ResourcesApi
        - Name: ILLIAD_BASE_URL
          Value: !Ref IlliadBaseUrl
        - Name: HOURS_API_URL
          Value: !Ref HoursApiUrl
        - Name: CONTENTFUL_API
          Value: !Ref ContentfulApi
      Source:
        Type: GITHUB
        Location: https://github.com/ndlib/usurper.git
        Auth:
          Type: OAUTH
      TimeoutInMinutes: 10
