AWSTemplateFormatVersion: "2010-09-09"
Description: "Buckets for CI stack"

Outputs:
  ArtifactBucket:
    Description: The artifact bucket for the build CI
    Value: !Ref ArtifactBucket

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ServiceName}-artifacts
      LifecycleConfiguration:
        Rules:
          - Id: SweepRule
            ExpirationInDays: 15
            Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-artifacts
