Service: usurper-ci

Stacks:
  Single:
    - Name: $SERVICE-$STAGE
      Template: root.yml
      Parameters:
        Repo: usurper
        Branch: ua
        OAuth: ${OAUTH}
        ServiceName: $SERVICE-$STAGE
        TemplateLoc: https://s3.amazonaws.com/$DEPLOY_BUCKET/$DEPLOY_FOLDER
        OutBucket: dev-staging.library.nd.edu
      Tags:
        Name: $SERVICE-$STAGE
        Owner: WSE
        Contact: WSE
        Description: CI for the Usurper Project
        InceptDate: $TIMESTAMP

Artifacts:
  Templates:
    - root.yml
    - buckets.yml
    - resources.yml
    - roles.yml
