AWSTemplateFormatVersion: "2010-09-09"
Description: "Resources for CI stack"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  Repo:
    Type: String
    Description: The name of the repo
  Branch:
    Type: String
    Description: The name of the branch in the repo
  OAuth:
    Type: String
    Description: The OAuth token to use for the repo
  RoleArn:
    Type: String
    Description: Arn of the Execution Role
  OutBucket:
    Type: String
    Description: Name of the output bucket
  HoursApiUrl:
    Type: String
  ContentfulApi:
    Type: String
  ArtifactBucket:
    Type: String
    Description: Name of the artifact bucket

Resources:
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ServiceName
      Description: !Sub ${Repo} Continuous Integration
      ServiceRole: !Ref RoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:7.0.0
        EnvironmentVariables:
        - Name: REACT_OUTPUT
          Value: !Ref OutBucket
        - Name: STAGE
          Value: prep
        - Name: GIT_BRANCH
          Value: master
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  AppPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Ref ServiceName
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/AWS-CodePipeline-Service
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: GithubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: ndlib
                Repo: !Ref Repo
                Branch: !Ref Branch
                OAuthToken: !Ref OAuth
              OutputArtifacts:
                - Name: SourceOutput
        -
          Name: Build
          Actions:
            -
              Name: BuildSource
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuiltProject
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Ref: BuildProject
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
