Parameters:
  Repo:
    Type: String
    Description: The name of the repo
  Branch:
    Type: String
    Description: The name of the branch in the repo
  OAuth:
    Type: String
    Description: The OAuth token to use for the repo
  ServiceName:
    Type: String
    Description: The Service name
  TemplateLoc:
    Type: String
    Description: The bucket url where these templates are stored
  OutBucket:
    Type: String
    Description: Name of the bucket to put the built website into

Resources:
  BucketsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateLoc}/buckets.yml
      Parameters:
        ServiceName: !Ref ServiceName

  RolesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: BucketsStack
    Properties:
      TemplateURL: !Sub ${TemplateLoc}/roles.yml
      Parameters:
        ServiceName: !Ref ServiceName
        OutBucket: !Ref OutBucket
        ArtifactBucket: !GetAtt BucketsStack.Outputs.ArtifactBucket

  ResourcesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesStack
    Properties:
      TemplateURL: !Sub ${TemplateLoc}/resources.yml
      Parameters:
        OutBucket: !Ref OutBucket
        ArtifactBucket: !GetAtt BucketsStack.Outputs.ArtifactBucket
        RoleArn: !GetAtt RolesStack.Outputs.RoleArn
        ServiceName: !Ref ServiceName
        Repo: !Ref Repo
        Branch: !Ref Branch
        OAuth: !Ref OAuth
