AWSTemplateFormatVersion: "2010-09-09"
Description: "Buckets for CI stack"

Outputs:
  ArtifactBucket:
    Description: The artifact bucket for the build CI
    Value: !Ref ArtifactBucket
  OutBucket:
    Description: The out bucket for the build CI
    Value: !Ref OutBucket

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ServiceName}-artifacts
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-artifacts

  OutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ServiceName}-built
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: Name
          Value: !Sub ${ServiceName}-built
